-- =====================================================================
-- 01. ROLES, USERS, WAREHOUSES & DATABASE SETUP
-- =====================================================================
USE ROLE ACCOUNTADMIN;

-- Create Dedicated Warehouse
CREATE WAREHOUSE IF NOT EXISTS DE_COMPUTE_WH
    WITH WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Virtual Warehouse for Data Engineering Ingestion Jobs';

-- Create Role Hierarchy
CREATE ROLE IF NOT EXISTS DE_ADMIN_ROLE;
CREATE ROLE IF NOT EXISTS DE_ETL_ROLE;

GRANT ROLE DE_ETL_ROLE TO ROLE DE_ADMIN_ROLE;
GRANT ROLE DE_ADMIN_ROLE TO ROLE ACCOUNTADMIN;

-- Grant Warehouse Usage to ETL Role
GRANT USAGE, OPERATE ON WAREHOUSE DE_COMPUTE_WH TO ROLE DE_ETL_ROLE;

-- Create Database and Schemas (Medallion Layers)
CREATE DATABASE IF NOT EXISTS OPEN_SOURCE_DB;

-- Schema setup
CREATE SCHEMA IF NOT EXISTS OPEN_SOURCE_DB.BRONZE_RAW COMMENT = 'Raw ingested data in JSON/Parquet format';
CREATE SCHEMA IF NOT EXISTS OPEN_SOURCE_DB.SILVER_STAGING COMMENT = 'Cleaned and flattened structured data';
CREATE SCHEMA IF NOT EXISTS OPEN_SOURCE_DB.GOLD_ANALYTICS COMMENT = 'Aggregated business-ready data model';

-- Grant Privileges on Database and Schemas to ETL Role
GRANT ALL PRIVILEGES ON DATABASE OPEN_SOURCE_DB TO ROLE DE_ADMIN_ROLE;
GRANT USAGE ON DATABASE OPEN_SOURCE_DB TO ROLE DE_ETL_ROLE;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE OPEN_SOURCE_DB TO ROLE DE_ETL_ROLE;
GRANT FUTURE PRIVILEGES ON SCHEMAS IN DATABASE OPEN_SOURCE_DB TO ROLE DE_ETL_ROLE;