-- =====================================================================
-- 05. CDC AUTOMATION WITH STREAMS & TASKS
-- =====================================================================
USE ROLE DE_ETL_ROLE;
USE WAREHOUSE DE_COMPUTE_WH;
USE DATABASE OPEN_SOURCE_DB;

-- 1. Create Stream on Bronze Table to track CDC changes
CREATE OR REPLACE STREAM BRONZE_RAW.STR_RAW_BREWERIES 
ON TABLE BRONZE_RAW.RAW_BREWERIES;

-- 2. Task 1 (Root): Automatically populate Silver Layer when Stream has new data
CREATE OR REPLACE TASK SILVER_STAGING.TASK_PROCESS_SILVER
    WAREHOUSE = DE_COMPUTE_WH
    SCHEDULE = 'USING CRON 0 0 1 1 * UTC'
    WHEN SYSTEM$STREAM_HAS_DATA('OPEN_SOURCE_DB.BRONZE_RAW.STR_RAW_BREWERIES')
AS
INSERT INTO OPEN_SOURCE_DB.SILVER_STAGING.DIM_BREWERIES
SELECT
    COALESCE(f.value:id::STRING, s.RAW_PAYLOAD:id::STRING),
    COALESCE(f.value:name::STRING, s.RAW_PAYLOAD:name::STRING),
    COALESCE(f.value:brewery_type::STRING, s.RAW_PAYLOAD:brewery_type::STRING),
    COALESCE(f.value:street::STRING, s.RAW_PAYLOAD:street::STRING),
    COALESCE(f.value:city::STRING, s.RAW_PAYLOAD:city::STRING),
    COALESCE(f.value:state_province::STRING, s.RAW_PAYLOAD:state_province::STRING),
    COALESCE(f.value:postal_code::STRING, s.RAW_PAYLOAD:postal_code::STRING),
    COALESCE(f.value:country::STRING, s.RAW_PAYLOAD:country::STRING),
    COALESCE(f.value:longitude::NUMBER(10,7), s.RAW_PAYLOAD:longitude::NUMBER(10,7)),
    COALESCE(f.value:latitude::NUMBER(10,7), s.RAW_PAYLOAD:latitude::NUMBER(10,7)),
    COALESCE(f.value:phone::STRING, s.RAW_PAYLOAD:phone::STRING),
    COALESCE(f.value:website_url::STRING, s.RAW_PAYLOAD:website_url::STRING),
    s.INGESTION_TIMESTAMP
FROM OPEN_SOURCE_DB.BRONZE_RAW.STR_RAW_BREWERIES s,
LATERAL FLATTEN(input => s.RAW_PAYLOAD, outer => true) f
WHERE s.METADATA$ACTION = 'INSERT';

-- 3. Task 2 (Child): Chain Gold Layer refresh upon completion of Task 1
CREATE OR REPLACE TASK SILVER_STAGING.TASK_REFRESH_GOLD
    WAREHOUSE = DE_COMPUTE_WH
    AFTER SILVER_STAGING.TASK_PROCESS_SILVER
AS
INSERT OVERWRITE INTO OPEN_SOURCE_DB.GOLD_ANALYTICS.FACT_BREWERY_SUMMARY_BY_STATE
SELECT
    COUNTRY,
    STATE_PROVINCE,
    BREWERY_TYPE,
    COUNT(DISTINCT BREWERY_ID),
    CURRENT_TIMESTAMP()
FROM OPEN_SOURCE_DB.SILVER_STAGING.DIM_BREWERIES
GROUP BY 1, 2, 3;

-- 4. Resume Tasks
ALTER TASK SILVER_STAGING.TASK_REFRESH_GOLD RESUME;
ALTER TASK SILVER_STAGING.TASK_PROCESS_SILVER RESUME;