-- =====================================================================
-- 05. CDC AUTOMATION WITH STREAMS & TASKS
-- =====================================================================
USE ROLE DE_ETL_ROLE;
USE WAREHOUSE DE_COMPUTE_WH;
USE DATABASE OPEN_SOURCE_DB;

-- 1. Create Stream on Bronze Table to track CDC changes
CREATE OR REPLACE STREAM BRONZE_RAW.STR_RAW_BREWERIES 
ON TABLE BRONZE_RAW.RAW_BREWERIES;

-- 2. Task 1 (Root): Automatically populate Silver Layer when Stream has new data
CREATE OR REPLACE TASK SILVER_STAGING.TASK_PROCESS_SILVER
    WAREHOUSE = DE_COMPUTE_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('OPEN_SOURCE_DB.BRONZE_RAW.STR_RAW_BREWERIES')
AS
INSERT INTO OPEN_SOURCE_DB.SILVER_STAGING.DIM_BREWERIES
SELECT
    RAW_PAYLOAD:id::STRING,
    RAW_PAYLOAD:name::STRING,
    RAW_PAYLOAD:brewery_type::STRING,
    RAW_PAYLOAD:street::STRING,
    RAW_PAYLOAD:city::STRING,
    RAW_PAYLOAD:state_province::STRING,
    RAW_PAYLOAD:postal_code::STRING,
    RAW_PAYLOAD:country::STRING,
    RAW_PAYLOAD:longitude::NUMBER(10,7),
    RAW_PAYLOAD:latitude::NUMBER(10,7),
    RAW_PAYLOAD:phone::STRING,
    RAW_PAYLOAD:website_url::STRING,
    INGESTION_TIMESTAMP
FROM OPEN_SOURCE_DB.BRONZE_RAW.STR_RAW_BREWERIES
WHERE METADATA$ACTION = 'INSERT';

-- 3. Task 2 (Child): Chain Gold Layer refresh upon completion of Task 1
-- (Both tasks reside in SILVER_STAGING schema so Snowflake permits the predecessor relation)
CREATE OR REPLACE TASK SILVER_STAGING.TASK_REFRESH_GOLD
    WAREHOUSE = DE_COMPUTE_WH
    AFTER SILVER_STAGING.TASK_PROCESS_SILVER
AS
INSERT OVERWRITE INTO OPEN_SOURCE_DB.GOLD_ANALYTICS.FACT_BREWERY_SUMMARY_BY_STATE
SELECT
    COUNTRY,
    STATE_PROVINCE,
    BREWERY_TYPE,
    COUNT(DISTINCT BREWERY_ID),
    CURRENT_TIMESTAMP()
FROM OPEN_SOURCE_DB.SILVER_STAGING.DIM_BREWERIES
GROUP BY 1, 2, 3;

-- 4. Resume Tasks (Child tasks must be resumed BEFORE parent/root tasks)
ALTER TASK SILVER_STAGING.TASK_REFRESH_GOLD RESUME;
ALTER TASK SILVER_STAGING.TASK_PROCESS_SILVER RESUME;
